title:            Resources 
#url:              http://japacible.github.io/
url:              localhost:4000
baseurl:          /res
permalink:        /:categories/:title.html
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-50444679-1
timezone:         America/Los_Angeles
